-- Creates system_settings table that V2 migration expects.
-- V1 (initial_spatial_schema) did not include this table; this migration
-- fills the gap so V2's ALTER TABLE succeeds in fresh environments.
CREATE TABLE IF NOT EXISTS system_settings (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unconfirmed_fencing_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    auto_threshold_seconds    BIGINT  NOT NULL DEFAULT 86400
);

INSERT INTO system_settings (unconfirmed_fencing_enabled, auto_threshold_seconds)
SELECT false, 86400
WHERE NOT EXISTS (SELECT 1 FROM system_settings);
